@startuml
skinparam linetype ortho
!$TEXTURE_ATLAS_COMPONENT = "true"

frame "Texture Atlas Component" as TextureAtlasComponent {
    class TextureAtlas
    TextureAtlas : -List<Texture>
    TextureAtlas : +AddTexture() Texture
    TextureAtlas : +GetTexture(id) Texture
    TextureAtlas : +GetTextureCount() Integer
    TextureAtlas --* Texture

    class Texture
    Texture : +GetIndex() Integer
    TextureAtlas : +GetAtlas() TextureAtlas
    Texture --> TextureAtlas
}

@enduml
