@startuml
skinparam linetype ortho

frame Core {
    ' !include Bones3.DataTypes.pu

    !include Bones3.WorldComponent.pu
    !include Bones3.RemeshComponent.pu
    !include Bones3.BlockTypesComponent.pu
    !include Bones3.TextureAtlasComponent.pu
    !include Bones3.WorldDatabaseComponent.pu
}

!include UnityImplementation.pu

@enduml
